kubecfg/kubecfg

cmd/show.go, cmd/show_test.go, pkg/kubecfg/show.go, pkg/kubecfg/show_test.go
In our internal project, we have almost 5000 individual YAML files that
we generate. For historic reasons, we continue to name the files .yml
instead of .yaml.
By enabling kubecfg to write the files with a .yml suffix, we can
produce these files for our CI/CD pipeline measurably faster.
I used hyperfine to benchmark the current mode (my build of kubecfg, do
not specify --format, followed by find | read | mv), vs. the same build
of kubecfg with --format=yml, no call to find.
Benchmark #1: GENMODE=current make generate
Time (mean ± σ):     13.384 s ±  0.459 s    [User: 79.086 s, System: 19.813 s]
Range (min … max):   12.775 s … 14.280 s    10 runs
Benchmark #2: GENMODE=newkubecfg make generate
Time (mean ± σ):     11.166 s ±  0.216 s    [User: 73.907 s, System: 9.905 s]
Range (min … max): …
=> Allow output filenames to have yml suffix

CONTRIBUTING.md, Makefile
I removed vendoring in #29 but forgot this command in the makefile.
Users who were used to run `make vendor` end up putting stuff back to `vendor/`, see #67
=> Remove go mod vendor from Makefile

pkg/kubecfg/update.go
Previously we would garbage collect a stale object by deleting it
through every API group and version through which it appeared.  In
practice, every version after the first one returned 'not found',
which was silently ignored.
Now we walk only the 'preferred' versions of each API group when
looking for stale objects.
As well as making fewer apiserver calls, this should avoid triggering
(safe but noisy) 'deprecated' warnings when we use old API versions.
Fixes #30.
=> Garbage collect only the 'preferred' version of resources

cmd/root.go, go.mod, go.sum
This PR bind the `KUBECFG_ALPHA` env var to the `--alpha` flag.
It uses the viper `autoenv` feature, but it only uses viper to access the `--alpha` flag (for now)
=> Bind --alpha to KUBECFG_ALPHA

cmd/completion.go, cmd/completion_test.go
Might as well include this, since it's supported. I wanted to add fish completion to the AUR pkg for kubecfg, so this is a necessary first step.
NOTES:
1. I tried to run `make generate` as advised by the contrib guide, but it doesn't seem to exist. Not sure what's going on there. Maybe those need an update?
2. I ran `make tidy` as a test, and it did produce various changes, notably
```
diff --git a/go.mod b/go.mod
index 193c90c..f1c7448 100644
--- a/go.mod
+++ b/go.mod
@@ -31,7 +31,6 @@ require (
)
require (
-       cloud.google.com/go v0.100.2 // indirect
```
but I decided not to include this in my PR, insofar as this seems like a pretty trivial change to me. Please advise if this is wrong.
3. I tested `./kubecfg completion > ~/.config/fish/completions/kubecfg.fish` on fish `3.5.1` and …
=> Fish completion

.github/renovate.json
This replicates the logic that renovatebot uses to update `go.mod` go version, so should stay in sync.
See the `golang-version` datasource and https://github.com/renovatebot/renovate/blob/3cec44cfa78e37a57c84e6428056787fc00ade7c/lib/modules/manager/gomod/extract.spec.ts#L22-L35
=> Teach renovatebot how to update github-action go-version

.github/workflows/go.yml
Once upon a time, there was no go-jsonnet, and `kubecfg` used cgo to link against a static (C++) libjsonnet.
When the dinosaurs downloaded this ancient pre-compiled kubecfg binary, it was important that it _was_ statically linked, and did not contain references to external shared libraries that those dinosaurs might not have had locally.   There was a line in the ancient build rituals to help detect and debug such issues.
Remove this long-obsolete reference to the ancient rituals, and let them pass into git history.
=> Remove ancient use of ldd

.github/renovate.json
Run `go mod tidy` and update import paths after updating go deps.
=> renovatebot: run go mod tidy after updating deps

.github/renovate.json
Sigh. I wondered if this mattered - turns out it does.  See `skipReason` in https://app.renovatebot.com/dashboard#github/kubecfg/kubecfg/789631133:
```json
"packageFile": ".github/workflows/go.yml",
"deps": [
{
"depName": "go",
"currentValue": "1.17",
"datasource": "golang-version",
"depType": "golang",
"replaceString": "go-version: 1.17\n",
"depIndex": 0,
"warnings": [],
"versioning": "semver",
"skipReason": "invalid-value",
"updates": []
}
],
```
`1.17` is not a valid version using the default 'semver' versioning scheme (must be 3 components).
Change to use more relaxed 'npm' version comparisons, again matching what is used in renovatebot `go.mod` updates.
=> Relax version syntax in go-version updater

.github/workflows/go.yml
Currently we're running `ko build` with default arguments which includes a hash of the import path of the binary in the repo name: [kubecfg/kubecfg-2ba4e5aa7403687d7ea49e0928bad159](https://github.com/orgs/kubecfg/packages/container/package/kubecfg%2Fkubecfg-2ba4e5aa7403687d7ea49e0928bad159)
we want to publish the container with a less confusing image name; the `-B` flag strikes a good balance: it still allows multiple docker images per project but makes the reasonable assumption that we'll name our binaries with unique names within this project. Hence, the image name will become `ghcr.io/kubecfg/kubecfg/kubecfg` (the first kubecfg is the org, the second is the repo name and the third is the binary)
=> Use docker image name without: ghcr.io/kubecfg/kubecfg/kubecfg

cmd/httpd.go, pkg/kubecfg/httpd.go
Implements a "http server" where the request handler is implemented in jsonnet.
The idea seems a bit crazy, but it's actually a quite dope way to implement k8s controllers by implementing [metacontroller](https://metacontroller.github.io/metacontroller/intro.html) hooks in jsonnet.
Example
```console
$ cat /tmp/ugo.jsonnet 
function(request) {
got: request,
message: 'ok',
}
$ make && ./kubecfg --alpha -J /tmp httpd ugo.jsonnet
CGO_ENABLED=0 go build  -tags netgo -installsuffix netgo -ldflags="-X main.version=dev-2022-12-20T15:52:22+0100-5ab1d34f " .
```
```console
$ curl  -d'{"bar":"baz"}' http://localhost:8080/ugo
{
"got": {
"bar": "baz"
},
"message": "ok"
}
```
This is just an alpha command meant for public experimentation, but no guarantees are made on API stability
=> Add simple stupid --alpha httpd command

cmd/completion.go, go.mod, go.sum, integration/completion_test.go
Upgrade cobra to v1.6.1 and fix integration test around zsh completion
=> chore: fix cobra upgrade integration test

go.mod, go.sum, utils/importer.go, utils/oci.go, utils/oci_test.go
```console
$ cat /tmp/imp.jsonnet                    
import 'oci://gcr.io/mkm-cloud/hello:v2'
$ make && ./kubecfg show /tmp/imp.jsonnet 
---
apiVersion: v1
data:
foo: bar baz
kind: ConfigMap
metadata:
name: demo
```
It implements a simple in-memory caching to avoid having to repeatedly interact with the remote OCI registry in the even of multiple relative imports from the same OCI package.
Like with `http://`, `oci://` works only in actual imports from within the jsonnet and the CLI arguments don't support urls (yet)
In order to create a package you have to use the `oras` tool:
```console
$ cat /tmp/demo.json
{
"entrypoint": "demo.jsonnet"
$ tree /tmp/demo
/tmp/demo
├── data.txt
└── demo.jsonnet
$ cat /tmp/demo/demo.jsonnet
{
config: {
apiVersion: 'v1',
kind: 'ConfigMap',
metadata: { …
```
=> Implement oci: url scheme

cmd/show_test.go, pkg/kubecfg/eval.go, pkg/kubecfg/httpd.go, utils/acquire.go
kubecfg already knows how to import files from various sources, like `http(s)` and `oci` urls. 
However, these urls are supported only from within `import` statements inside jsonnet and the CLI arguments accepted only files.
=> Allow URL in CLI arguments

cmd/delete.go, cmd/diff.go, cmd/eval.go, cmd/root.go, cmd/show.go, cmd/show_test.go, cmd/update.go, cmd/validate.go, utils/acquire.go
(Please review but **do not merge** until the `url-cli` branch is merged)
The `jsonnet` CLI tool allows to run jsonnet code directly from the cli arguments instead of requiring it to be loaded from files.
e.g.:
```console
$ jsonnet -e "{apiVersion: 'v1', kind: 'ConfigMap', metadata: {name: 'foo'}}"   
{
"apiVersion": "v1",
"kind": "ConfigMap",
"metadata": {
"name": "foo"
}
}
```
This PR gives `kubecfg` the same functionality:
```console
$ kubecfg show -e "{apiVersion: 'v1', kind: 'ConfigMap', metadata: {name: 'foo'}}"
---
apiVersion: v1
kind: ConfigMap
metadata:
name: foo
```
It can be useful to do things like:
```console
$ kubecfg update -e "(import 'foo.jsonnet') + (import 'overlay.jsonnet')"
```
=> Add support for inline code with -e

go.mod, go.sum, utils/oci.go, utils/oci_test.go
I initially implemented OCI caching using an off the shelf http cache library. That's inadequate because:
1. the httpcache library I chose doesn't cache `HEAD` requests
2. I underestimated the overhead of rescanning the whole targz archive every time an import needs to be resolved.
This led to delays of up to 60s (!) when trying oci imports for real-world bundles containing more than a hundled jsonnet/libsonnet/json (and other data) files.
This PR takes another approach: whenever a file over the OCI scheme is imported for the first time, we create a "oci bundle" structure populated with a map of filename -> file content, and add it to a map of "package" -> "bundle".
The package contains the tag and/or sha, as provided in the import url.
--
This also fixes an issue where if the entrypoint …
=> Rework OCI caching

cmd/common.go, cmd/completion.go, cmd/delete.go, cmd/diff.go, cmd/eval.go, cmd/httpd.go, cmd/pack.go, cmd/show.go, cmd/update.go, cmd/validate.go
This is no-effect refactoring that will pave the way for adding more common flags to all the commands that evaluate some jsonnet  (update,show,eval,delete,validate)
=> Refactor common eval flags

cmd/pack_test.go, cmd/show_test.go
1. make `resetFlagsOf()` recursively reset flags of subcommands
2. make `cmdOutput` reset flags after running the command
3. remove all explicit calls of resetFlags which are easy to forget
4. undo hack in pack_test.go
=> Fix resetFlags helper

cmd/common.go, cmd/show_test.go, examples/guestbook-overlay.jsonnet, testdata/configmap.jsonnet, testdata/namespace-overlay.jsonnet, testdata/secret.jsonnet
Implements an alpha feature that allows to apply overlays more easily. Demo:
```console
$ export KUBECFG_ALPHA=1
$ ./kubecfg show ./testdata/configmap.jsonnet
---
apiVersion: v1
kind: ConfigMap
metadata:
name: test
$ ./kubecfg show ./testdata/configmap.jsonnet --overlay ./testdata/namespace-overlay.jsonnet
---
apiVersion: v1
kind: ConfigMap
metadata:
name: test
namespace: myns
```
This is basically a CLI syntactical sugar for:
```console
$  ./kubecfg show -e "(import './testdata/configmap.jsonnet') + (import './testdata/namespace-overlay.jsonnet')"
```
(which in turn is syntactical sugar for `kubecfg show 'data:,%28import%20%27...'`)
It works for all commands that accept jsonnet arguments (show,update,delete,validate,...).
If there are multiple jsonnet files, the same overlay is applied …
=> Add --overlay flag

cmd/root.go, pkg/kubecfg/vars/vars.go, pkg/kubecfg/vm.go
Currently the only way to create a jsonnet.VM with all the appropriate import hooks and whatnot is to call the JsonnetVM function in the `cmd` package, Unfortunately the cmd package is intimately tied to the cobra command+flag parsing framework which makes using kubecfg as a library from another project particularly painful, ugly and brittle.
kubecfg is more than just a cli around jsonnet; it adds import hooks for a few url formats (http, oci) and providers other features.
This PR is a first in a short series meant to make the kubecfg engine easier to use from other projects.
In particular, this PR moves `cmd.JsonnetVM(*cobra.Cmd)` into `kubecfg.JsonnetVM(opts...)`.
It lifts all the configurable bits into optional options (following Pike's option pattern …
=> chore: Factor out JsonnetVM constructor

cmd/root.go, pkg/kubecfg/vm.go
This allows one to use kubecfg as a library. Example:
```go
vm, err := kubecfg.JsonnetVM(kubecfg.WithImportPath("lib"))
if err != nil {
return nil, err
}
objs, err := kubecfg.ReadObjects(vm, paths, utils.WithProvenance(true))
if err != nil {
return nil, err
}
```
=> chore: Make ReadObjects public

utils/acquire.go
```console
$ kubecfg show testdata/lib/test.libsonnet      
ERROR error reading testdata/lib/test.libsonnet: unknown file extension: testdata/lib/test.libsonnet
```
In the real world it's not uncommon to have `.libsonnet` files containing k8s objects you want to evaluate i.e. it's not like everybody only ever uses `.libsonnet` to keep strictly library stuff like functions etc. Sometimes people have a concept of a "component library", and decide that "libsonnet" file extension may well fit.
I'm not sure we're only supporting `.jsonnet` file extension for any reason other than not having explicitly added the `.libsonnet` extension to this switch case.
=> Accept .libsonnet files as jsonnet sources

cmd/common.go, cmd/delete.go, cmd/diff.go, cmd/eval.go, cmd/root.go, cmd/show.go, cmd/show_test.go, cmd/update.go, cmd/validate.go
The `--overlay` flag is an alpha feature that allows users to quickly apply an overlay on a jsonnet file, directly from the CLI.
During initial alpha testing of the feature, it became clear that we more often needed to apply an overlay where the jsonnet source of the overlay appears as literal code snippet in in the CLI flags (as opposed to applying an overlay from a file).
The rationale for that is that when you have overlays in files, it's more common to just import the file meant to be overlaid and then apply the overlay: `(import "base.jsonnet")  { foo: 1 }`.
That said, it's still useful to sometimes decouple the overlay from the files to overlay.
We have already an established flag pattern to distinguish "literal code" from "code from file", and we use it in the `--ext-*` and …
=> Systematize --overlay-* flags to follow pattern of --ext-var and --tla

pkg/kubecfg/pack.go
This allows the kubecfg jsonnet bundles to be ferried around by the fluxcd ocirepository controller.
```console
$ flux pull artifact oci://gcr.io/mkm-cloud/dummy:k1 -o /tmp/unpack
✔ source kubecfg pack
✔ revision unknown
✔ digest gcr.io/mkm-cloud/dummy@sha256:9d44fe2ee54fa7a6850bc46b3da7a37779f18bff832a07c77550773e39c1d1f6
✔ artifact content extracted to /tmp/unpack
$ tree /tmp/unpack
```
=> feat: Compatibility with ocireposource

.github/workflows/go.yml
PRs like https://github.com/kubecfg/kubecfg/pull/284 which come from forks, always fail their CI build because as part of the tests we build a docker image and push it to the GHCR repo. I like that feature because it allows me to test the images before merging a PR. But I don't know how to make the permissions work for PRs that come from forks.
=> chore: Skip OCI push if PR comes from fork

pkg/kubecfg/show_test.go, pkg/kubecfg/update.go, utils/resolver.go
Run `go fmt` across the project.
Building off of https://github.com/kubecfg/kubecfg/pull/284#issuecomment-1635617990, I (and likely others) have an automatic `go fmt` on save for a file.
Having this already done will avoid large, unrelated diffs when touching different files in the project.
=> chore: format files via go fmt

go.mod, go.sum, lib/kubecfg.libsonnet, utils/nativefuncs.go, utils/nativefuncs_test.go
Adds the `validateJSONSchema` functionality to `kubecfg` so that a schema can be provided against a particular object. If this validation fails, a stream of errors are produced to `stderr` - under the common `RUNTIME ERROR: ...`.
This is a little rough around the edges, so any feedback is appreciated :smile:
=> feat: add `validateJSONSchema` native function

pkg/kubecfg/httpd.go
Move execution of `vm.evaluateSnippet` and resolution of `jsonnet filename` to the `Run `function.
**I am not sure why** but with the previous code when using `multiple jsonnet hooks` like 
`kubecfg --alpha httpd sync-hook1.jsonnet sync-hook2.jsonnet` the `last file` was always called for all hooks
then when hitting `:8080/sync-hook1` the `sync-hook2.jsonnet` was executed 
---
* add Logging of HOOKs definition and execution
```
➜ git diff | cat
diff --git a/pkg/kubecfg/httpd.go b/pkg/kubecfg/httpd.go
index 567a05e..1b65957 100644
--- a/pkg/kubecfg/httpd.go
+++ b/pkg/kubecfg/httpd.go
@@ -7,6 +7,7 @@ import (
"net/http"
"strings"
+   log "github.com/sirupsen/logrus"
"github.com/google/go-jsonnet"
"github.com/kubecfg/kubecfg/utils"
)
@@ -33,7 +34,9 @@ func evaluateFile(vm *jsonnet.VM, path …
```
=> Fix Hook name to jsonnet code execution

.github/workflows/go.yml
* Replace `setup-ko` action with official one from `ko-build` ( same version of binary is installed ) 
* Add a step to push image with `kubecfg:${GITHUB_TAG}` when the action is run on a tag / release
see build on my fork
=> Add build of docker image with TAG

.ko.yaml
* Add same flags we use through Makefile
* "VERSION" and "GO_LDFLAGS" are already set in the workflow `go.yaml`
* Expose version in docker image 
```
➜ docker run --rm ghcr.io/primeroz/kubecfg/kubecfg:v0.0.2-fc-test1 version
kubecfg version: v0.0.2-fc-test1
jsonnet version: v0.20.0
```
=> Add .ko.yaml configuration to set Build Flags

pkg/kubecfg/pack.go, pkg/kubecfg/pack_test.go
`kubecfg pack` doesn't work when the jsonnet to pack has only one file.
```console
$ kubecfg pack --alpha gcr.io/mkm-cloud/package-demo:v1 $HOME/tmp/shell.jsonnet --output /tmp/output.tar.gz && tar tvfz /tmp/output.tar.gz
tar: Archive entry has empty or unreadable filename ... skipping.
tar: Error exit delayed from previous errors.
```
There is a bug in the function that strips the common directory parts.
This PR fixes the bug and adds a few test cases.
```console
$ go build && ./kubecfg pack --alpha gcr.io/mkm-cloud/package-demo:v1 $HOME/tmp/shell.jsonnet --output /tmp/output.tar.gz && tar tvfz /tmp/output.tar.gz
-rw-rw-rw-  0 0      0        1078 Jan  1  1970 shell.jsonnet
=> fix: test short names and fix bug

cmd/pack_test.go, cmd/version.go, main.go, pkg/kubecfg/pack.go, pkg/version/version.go, utils/oci.go
NOTE: `kubecfg pack` is still behind `--alpha` feature flag. This is an experiment.
When creating an OCI package with `kubecfg pack`, we currently record only the filename of the entrypoint in the metadata.
It would be useful to contain other metadata but we don't know yet which metadata will be useful.
This PR adds a `metadata` field in the bundle config which will contain a JSON object which should have top level keys scoped by metadata type, possibly tool specific.
For example:
```json
{
"entrypoint": "shell.jsonnet",
"metadata": {
"kubit.kubecfg.dev/v1alpha1": {
"minKubecfgVersion": "v0.30.0"
},
"pack.kubecfg.dev/v1alpha1": {
"version": "v0.31.4"
}
}
}
```
The custom metadata is obtained by evaluating an `$._kubecfg_pack_metadata` expression on the root jsonnet and gracefully handling …
=> feat: kubecfg pack metadata. kubecfg version + custom metadata

.ko.yaml
I need to run the kubecfg container an put the output in a file; I could add a flag just for that or I could just include bash in the image. The shell is likely useful for many other usecases of running kubecfg in a container.
=> Use base image with shell

lib/kubecfg.libsonnet, utils/nativefuncs.go, utils/nativefuncs_test.go
Updates `parseHelmChart` to support passing `capabilities` to be passed as `chartutil.Capabilities` to the helm chart renderer. Right now, only `KubeVersion` is able to be passed. This is important for rendering helm charts that conditionally render `apiVersion`s, among other fields, based on the current Kubernetes Cluster. The [default is `1.20`](https://github.com/helm/helm/blob/f31d4fb3aacabf6102b3ec9214b3433a3dbf1812/pkg/chartutil/capabilities.go#L31) which doesn't work for all use cases.
I wasn't sure if this is the best approach, nor is this currently an `optional` field (I will figure that out here soon). I wanted to send this out as proposal PR as well as to get feedback. We need this where I work currently, so I'm very motivated to get this working!
Thank you ✨
=> feat(parseHelmChart): support passing capabilities

cmd/pack.go, pkg/kubecfg/pack.go, utils/oci.go
```console
$ ./kubecfg --alpha pack --insecure-registry localhost:5050/demo:v123 testdata/configmap.jsonnet --docs-tar-file demo.tgz
$ crane manifest --insecure localhost:5050/demo:v123 | jq
{
"schemaVersion": 2,
"config": {
"mediaType": "application/vnd.kubecfg.bundle.config.v1+json",
"digest": "sha256:2c388e6044e638e18c8ef4fb4593500db482b47fa4dc95fa7fc96209fb2aa428",
"size": 101
},
"layers": [
{
"mediaType": "application/vnd.kubecfg.bundle.tar+gzip",
"digest": "sha256:779e3aca133f6d8573ed50f2ab4d2e86eef7cf351a4142be6363e3720b2d823d",
"size": 173
},
{
"mediaType": "application/vnd.kubecfg.bundle.docs.tar+gzip",
"digest": "sha256:de446e611755b322769e2f41fbaceb571f6db401efc6ff1475b5cb941bbef603",
"size": 203631
}
],
"annotations": {
"org.opencontainers.image.created": …
```
=> feat: Add --docs-tar-file flag to pack

lib/kubecfg.libsonnet, testdata/kubecfg_test.jsonnet
This adds the following functions:
- `getPath(obj, path, default=null, inc_hidden=true)`
- `objectHasPath(obj, path, inc_hidden=false)`
- `objectHasPathAll(obj, path)`
into the `kubecfg.libsonnet` file.
This is shorthand for needing to do something which looks like this for nested objects:
```
if std.objectHas(myObj, "foo") && std.objectHas(myObj.foo, "bar") && ...
```
This was adapted from an [old jsonnet mailing list](https://groups.google.com/g/jsonnet/c/1nEJOYmS78I/m/uQ-g-9A3BwAJ) and morphed to be more inline with the standard library implementations for the respective `jsonnet` functions.
=> feat: add `getPath`/`objectHasPath`/`objectHasPathAll` functions for access to nested objects

pkg/kubecfg/eval.go
Remove the duplicate `err != nil` check here, the `pathURL` already has the check. I suspect that this is left over from a merge conflict sometime ago.
Spotted whilst I was browsing through for something else 😄 
This is probably easiest to show from the `main` branch:
https://github.com/kubecfg/kubecfg/blob/c8b7e6ade9a955af29fa5ac6eb18e3c7cc181872/pkg/kubecfg/eval.go#L31-L38
=> fix: remove duplicate err check

cmd/pack.go, pkg/kubecfg/pack.go
closes #447 
e.g.:
```console
$ kubecfg --alpha pack \
--annotation my-domain.com/my-repo-commit-sha=252e791916a082b075f6d84daf46ec8545482b7e648f8208f81f3f4e4c728a \
--annotation my-domain.com/pull-request=https://github.com/my-org/my-repo/pull/123
```
=> feat: --annotation cli arg for pack command

.github/workflows/go.yml
i'm using `kubecfg` in a multi-platform image, built on self-hosted GitHub Actions runners. for some reason, one of the dependencies of `kubecfg` causes the `go install` to take a **very** long time (the whole image build takes 30 min; most of it is the `go install`).
if `kubecfg` published a linux arm build alongside the linux x64 build, then i could install both via `curl` instead of `go install`
refs:
- [docs on linux arm runners](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#choosing-github-hosted-runners)
=> ci: support linux/arm64 builds
